#           ( Type,   TaskName, DeviceName(createPhyChan),TriggerChannel, SigType, ClockChannel)
createDevice("NI6123", "Dev2_AI", "Dev2", "/Dev2/PFI0", "ai",  "/Dev2/PFI12")

#            ( TaskName, ChannelID, InputType, TagName, arg(MDS_Param or SCXI phyChannel))
createChannel("Dev2_AI",     "0",     "SXR",  "SXR041",     "Dev2/ai0")
createChannel("Dev2_AI",     "1",     "SXR",  "SXR042",     "Dev2/ai1")
createChannel("Dev2_AI",     "2",     "SXR",  "SXR043",     "Dev2/ai2")
createChannel("Dev2_AI",     "3",     "SXR",  "SXR044",     "Dev2/ai3")
createChannel("Dev2_AI",     "4",     "SXR",  "SXR045",     "Dev2/ai4")
createChannel("Dev2_AI",     "5",     "SXR",  "SXR046",     "Dev2/ai5")
createChannel("Dev2_AI",     "6",     "SXR",  "SXR047",     "Dev2/ai6")
createChannel("Dev2_AI",     "7",     "SXR",  "SXR048",     "Dev2/ai7")
