#           ( Type,   TaskName, DeviceName(createPhyChan),TriggerChannel, SigType, ClockChannel)
createDevice("NI6123", "Dev7_AI", "Dev7", "/Dev7/PFI0", "ai",  "/Dev7/PFI12")

#            ( TaskName, ChannelID, InputType, TagName, arg(MDS_Param or SCXI phyChannel))
#createChannel("Dev1_AI",    "0",     "AI",  "TEMP1","")
#createChannel("Dev1_AI",    "1",     "AI",  "TEMP2","")
createChannel("Dev7_AI",     "0",     "SXR",  "SXR001",     "Dev7/ai0")
createChannel("Dev7_AI",     "1",     "SXR",  "SXR002",     "Dev7/ai1")
createChannel("Dev7_AI",     "2",     "SXR",  "SXR003",     "Dev7/ai2")
createChannel("Dev7_AI",     "3",     "SXR",  "SXR004",     "Dev7/ai3")
createChannel("Dev7_AI",     "4",     "SXR",  "SXR005",     "Dev7/ai4")
createChannel("Dev7_AI",     "5",     "SXR",  "SXR006",     "Dev7/ai5")
createChannel("Dev7_AI",     "6",     "SXR",  "SXR007",     "Dev7/ai6")
createChannel("Dev7_AI",     "7",     "SXR",  "SXR008",     "Dev7/ai7")
