TOP=../..
include $(TOP)/configure/CONFIG

DB += SYS_CLTU.db
DB += SYS_CLTU_CFG.db

# it depence on local system name !!!!!!!!!!!!!!
# should copy template to local directory.
DB += TSS_CLTU_CFG.template
DB += XXX_CLTU_CFG.template
#DB += XXX_MTRIG_P0_CFG.template
#DB += XXX_MTRIG_P1_CFG.template


include $(TOP)/configure/RULES

