TOP = ../..

include $(TOP)/configure/CONFIG

LIBRARY_IOC_vxWorks += vmivme2534

#DBDINC += 
DBD += devVmic2534.dbd

vmivme2534_SRCS_vxWorks += drvVmic2534.c
vmivme2534_SRCS_vxWorks += devVmic2534.c

include $(TOP)/configure/RULES

