#+======================================================================
#
# The PXI-6259 driver.
# Author: Janez Golob (Cosylab)
# Copyright (C) 2010-2013 ITER Organization
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file COPYING in the main directory of the Linux
# distribution for more details.
#
#+======================================================================

MODULE_NAME = pxi6259


# if you want to turn the debug messages on please uncomment one of the
# following lines depending on debug severity.

#CFLAGS += -D PXI6259_DEBUG -D PXI6259_VDEBUG
#EXTRA_CFLAGS += -D PXI6259_DEBUG -D PXI6259_VDEBUG

$(MODULE_NAME)-objs = pxi-6259-drv.o
obj-m = $(MODULE_NAME).o

