#======================================================================
# Compiling SDN library
#======================================================================

all:
	cd src/main/c++/sdn-api/ ; make all

clean:
	cd src/main/c++/sdn-api/ ; make clean

install: all
