TOP = ..
include $(TOP)/configure/CONFIG

LIBRARY_IOC += kutil

INC += kutil.h
INC += kutilObj.h
INC += kuTypes.h
INC += kuCommon.h
INC += kuDebug.h
INC += kuTime.h
INC += kuThread.h
INC += kuStd.h
INC += kuFile.h
INC += kuLock.h

DBD += kutil.dbd

SRCS += kuDebug.cpp
SRCS += kuTime.cpp
SRCS += kuThread.cpp
SRCS += kuStd.cpp
SRCS += kuFile.cpp
SRCS += kuLock.cpp

include $(TOP)/configure/RULES
