/******************************************************************************
 *  Copyright (c) 2010 ~ by NFRI, Woong. All Rights Reserved.                     *
 ******************************************************************************/

/*==============================================================================
                        EDIT HISTORY FOR MODULE


2007. 11. 23.
first created by woong.

2013. 3. 19
FPGA major updated.

*/


#ifndef _IOCTL_CLTU_H_
#define _IOCTL_CLTU_H_


#define IOCTL_XTU_MAGIC 't'

typedef struct
{
	unsigned long size;
	unsigned char buff[128];
} __attribute__((packed)) ioctl_cltu_info;

/*
typedef struct int_arg_t
{
	struct semaphore sem_cb;
	int nVal;
	
} CLTU_INTERRUPT_CALLBACK;
*/


#define IOCTL_XTU_GETSTATE		_IO( IOCTL_XTU_MAGIC, 0 )

#define IOCTL_XTU_READ        _IO( IOCTL_XTU_MAGIC, 1 )
#define IOCTL_XTU_WRITE       _IO( IOCTL_XTU_MAGIC, 2 )
#define IOCTL_XTU_INTERRUPT_ATTACH       _IO( IOCTL_XTU_MAGIC, 3 )
#define IOCTL_XTU_INTERRUPT_ENABLE   _IO( IOCTL_XTU_MAGIC, 4 )
#define IOCTL_XTU_INTERRUPT_DISABLE   _IO( IOCTL_XTU_MAGIC, 5 )
/*

#define IOCTL_XTU_SETUP_PORT   _IO( IOCTL_XTU_MAGIC, 6 )
#define IOCTL_XTU_NODE_ID   _IO( IOCTL_XTU_MAGIC, 8 )
#define IOCTL_XTU_GET_CAL_TICK   _IO( IOCTL_XTU_MAGIC, 9 )
#define IOCTL_XTU_GET_CAL_ID   _IO( IOCTL_XTU_MAGIC, 10 )


#define IOCTL_XTU_GET_FPGA_VER   _IO( IOCTL_XTU_MAGIC, 12 )
#define IOCTL_XTU_GET_ENDIAN   _IO( IOCTL_XTU_MAGIC, 13 )
#define IOCTL_XTU_GET_REF_CLOCK   _IO( IOCTL_XTU_MAGIC, 14 )
#define IOCTL_XTU_GET_IRIGB  _IO( IOCTL_XTU_MAGIC, 15 )
#define IOCTL_XTU_GET_IRIGB_UNLOCK_CNT   _IO( IOCTL_XTU_MAGIC, 16 )
#define IOCTL_XTU_GET_SERDES	_IO( IOCTL_XTU_MAGIC, 17 )
#define IOCTL_XTU_GET_FOT_RXLINK	_IO( IOCTL_XTU_MAGIC, 18 )


#define IOCTL_XTU_GET_CURRENT_TIME	_IO( IOCTL_XTU_MAGIC, 19 )
#define IOCTL_XTU_GET_CURRENT_TICK	_IO( IOCTL_XTU_MAGIC, 20 )

#define IOCTL_XTU_GET_SERDES_RX_CNT	_IO( IOCTL_XTU_MAGIC, 21 )
#define IOCTL_XTU_GET_SERDES_TX_CNT	_IO( IOCTL_XTU_MAGIC, 22 )

#define IOCTL_XTU_GET_STARTTIME_FROM_CTU	_IO( IOCTL_XTU_MAGIC, 23 )
#define IOCTL_XTU_GET_STARTTICK_FROM_CTU	_IO( IOCTL_XTU_MAGIC, 24 )
#define IOCTL_XTU_GET_ENDTIME_FROM_CTU	_IO( IOCTL_XTU_MAGIC, 25 )
#define IOCTL_XTU_GET_ENDTICK_FROM_CTU	_IO( IOCTL_XTU_MAGIC, 26 )

#define IOCTL_XTU_GET_STARTTIME_FROM_LTU	_IO( IOCTL_XTU_MAGIC, 27 )
#define IOCTL_XTU_GET_STARTTICK_FROM_LTU	_IO( IOCTL_XTU_MAGIC, 28 )
#define IOCTL_XTU_GET_ENDTIME_FROM_LTU	_IO( IOCTL_XTU_MAGIC, 29 )
#define IOCTL_XTU_GET_ENDTICK_FROM_LTU	_IO( IOCTL_XTU_MAGIC, 30 )


#define IOCTL_XTU_GET_REG_0	_IO( IOCTL_XTU_MAGIC, 31 )

*/


#define IOCTL_XTU_SET_ENDIAN   _IO( IOCTL_XTU_MAGIC,					6 )
#define IOCTL_XTU_SET_MODE   _IO( IOCTL_XTU_MAGIC, 						7 )
#define IOCTL_XTU_SET_DBG_MODE   _IO( IOCTL_XTU_MAGIC, 					8)
#define IOCTL_XTU_SET_LOCAL_TIME   _IO( IOCTL_XTU_MAGIC, 				9 )
#define IOCTL_XTU_SET_CTU_DEFAULT_DELAY   _IO( IOCTL_XTU_MAGIC, 			10 )
#define IOCTL_XTU_SET_LTU_DELAY   _IO( IOCTL_XTU_MAGIC, 				11 )
#define IOCTL_XTU_SET_PORT_ACTIVE_LEVEL   _IO( IOCTL_XTU_MAGIC,		12 )
#define IOCTL_XTU_SET_PORT_CTL   _IO( IOCTL_XTU_MAGIC, 					13 )
#define IOCTL_XTU_SET_PORT_NHLI_NUM   _IO( IOCTL_XTU_MAGIC, 					14 )
#define IOCTL_XTU_SET_PORT_HLI   _IO( IOCTL_XTU_MAGIC, 					15 )
#define IOCTL_XTU_SET_PORT_LLI   _IO( IOCTL_XTU_MAGIC, 					16 )
#define IOCTL_XTU_SELECT_PORT   _IO( IOCTL_XTU_MAGIC, 					17 )
#define IOCTL_XTU_SELECT_HLI   _IO( IOCTL_XTU_MAGIC, 					18 )
#define IOCTL_XTU_SELECT_LLI   _IO( IOCTL_XTU_MAGIC, 						19 )
#define IOCTL_XTU_SET_SHOT_TIME   _IO( IOCTL_XTU_MAGIC, 				20 )
#define IOCTL_XTU_SHOT_START   _IO( IOCTL_XTU_MAGIC, 					21 )
#define IOCTL_XTU_SHOT_END   _IO( IOCTL_XTU_MAGIC, 						22 )

#define IOCTL_XTU_SET_IRIGB_SRC   _IO( IOCTL_XTU_MAGIC, 					23 )
#define IOCTL_XTU_SET_CLK_CONFIG   _IO( IOCTL_XTU_MAGIC, 				24 )

#define IOCTL_XTU_GET_ENDIAN_CHECK  _IO( IOCTL_XTU_MAGIC, 				25 )
#define IOCTL_XTU_GET_CLK_CONFIG  _IO( IOCTL_XTU_MAGIC, 				26 )
#define IOCTL_XTU_GET_DBG_CONFIG  _IO( IOCTL_XTU_MAGIC, 				27 )
#define IOCTL_XTU_GET_CLK_STATUS  _IO( IOCTL_XTU_MAGIC, 				28 )
#define IOCTL_XTU_GET_SEL_XTU_MODE  _IO( IOCTL_XTU_MAGIC, 				29 )
#define IOCTL_XTU_GET_SEL_IRIGB  _IO( IOCTL_XTU_MAGIC, 					30 )
#define IOCTL_XTU_GET_TX_CURR_TIME  _IO( IOCTL_XTU_MAGIC, 				31 )
#define IOCTL_XTU_GET_TX_CURR_TIME_4  _IO( IOCTL_XTU_MAGIC, 			32 )
#define IOCTL_XTU_GET_TX_CURR_TIME_8  _IO( IOCTL_XTU_MAGIC, 			33 )
#define IOCTL_XTU_GET_TX_COMP_DELAY  _IO( IOCTL_XTU_MAGIC,			34 )
#define IOCTL_XTU_GET_TX_SHOT_TIME  _IO( IOCTL_XTU_MAGIC, 				35 )
#define IOCTL_XTU_GET_TX_SHOT_TIME_4  _IO( IOCTL_XTU_MAGIC, 			36 )
#define IOCTL_XTU_GET_TX_SHOT_TIME_8  _IO( IOCTL_XTU_MAGIC, 			37 )
#define IOCTL_XTU_GET_TX_SHOT_TIME_16  _IO( IOCTL_XTU_MAGIC, 			38 )
#define IOCTL_XTU_GET_TX_SHOT_TIME_20  _IO( IOCTL_XTU_MAGIC, 			39 )
#define IOCTL_XTU_GET_TX_SHOT_TIME_24  _IO( IOCTL_XTU_MAGIC, 			40 )

#define IOCTL_XTU_GET_RX_CURR_TIME  _IO( IOCTL_XTU_MAGIC, 				41 )
#define IOCTL_XTU_GET_RX_CURR_TIME_4  _IO( IOCTL_XTU_MAGIC, 			42 )
#define IOCTL_XTU_GET_RX_CURR_TIME_8  _IO( IOCTL_XTU_MAGIC, 			43 )
#define IOCTL_XTU_GET_RX_COMP_DELAY  _IO( IOCTL_XTU_MAGIC, 			44 )
#define IOCTL_XTU_GET_RX_SHOT_TIME  _IO( IOCTL_XTU_MAGIC, 				45 )
#define IOCTL_XTU_GET_RX_SHOT_TIME_4  _IO( IOCTL_XTU_MAGIC, 			46 )
#define IOCTL_XTU_GET_RX_SHOT_TIME_8  _IO( IOCTL_XTU_MAGIC, 			47 )
#define IOCTL_XTU_GET_RX_SHOT_TIME_16  _IO( IOCTL_XTU_MAGIC, 			48 )
#define IOCTL_XTU_GET_RX_SHOT_TIME_20  _IO( IOCTL_XTU_MAGIC, 			49 )
#define IOCTL_XTU_GET_RX_SHOT_TIME_24  _IO( IOCTL_XTU_MAGIC, 			50 )

#define IOCTL_XTU_GET_LOG_GSHOT  _IO( IOCTL_XTU_MAGIC, 				51 )
#define IOCTL_XTU_GET_LOG_PORT  _IO( IOCTL_XTU_MAGIC, 					52 )

#define IOCTL_XTU_SET_READ_OFFSET  _IO( IOCTL_XTU_MAGIC, 				53 )
#define IOCTL_XTU_SET_PERMANENT_CLK  _IO( IOCTL_XTU_MAGIC, 			54 )

#define IOCTL_XTU_GET_VENDOR_ID  _IO( IOCTL_XTU_MAGIC, 				55 )
#define IOCTL_XTU_GET_DEVICE_ID  _IO( IOCTL_XTU_MAGIC, 					56 )
#define IOCTL_XTU_GET_VERSION  _IO( IOCTL_XTU_MAGIC, 					57 )




#define IOCTL_XTU_MAXNR			58



#endif /* _IOCTL_CLTU_H_ */

