#!/bin/bash
export EPICS_CA_ADDR_LIST="172.17.101.142"
start=0
while [ $start -lt 1400 ]
do
echo "Do loof test Fuel DAQ : $start"
caput FUEL_DAQ_CREATE_LOCAL_TREE 20128105
sleep 2
caput FUEL_DAQ_SYS_ARMING 1
sleep 2
caput FUEL_DAQ_SYS_RUN 1
sleep 180
let start+=1
done

