TOP = ..
include $(TOP)/configure/CONFIG

TPG262 = $(TOP)/TPG262Lib

LIBRARY_IOC += TPG262

INC += drvTPG262.h
DBD += drvTPG262.dbd
DBD += devTPG262.dbd
TPG262_SRCS += drvTPG262.c
TPG262_SRCS += devTPG262.c

include $(TOP)/configure/RULES
