TOP = ../..

include $(TOP)/configure/CONFIG

LIBRARY_IOC_vxWorks += vmivme3122
DBD += devVmic3122.dbd
vmivme3122_SRCS_vxWorks += devAiVmi3122.c
vmivme3122_SRCS_vxWorks += devAoVmi3122.c
vmivme3122_SRCS_vxWorks += drvVmi3122.c
include $(TOP)/configure/RULES
