HdSize auto
Group Misc Tags
FRate_0 120
ITime_0 0.01
xmrCameraName SC6000
Group Instrument Info
IHFOV 1165.05
IVFOV 1165.05
SBPLo 3
SBPUp 5
SltRng 5
Group EUD Info
BgType_0 none
BgValu_0 0
Coeff0_0 -0.00113272
Coeff1_0 7.8236e-007
Coeff2_0 1.56591e-009
Coeff3_0 -4.59221e-014
DaUnit W/(sr-cm^2)
DaUnit_0 W/(sr-cm^2)
EuRaw Raw
EuRaw_0 Raw
PolyOrder_0 3
StdUnt 17
StdUnt_0 17
TempCoeff0_0 68.5143
TempCoeff1_0 13557.2
TempCoeff2_0 -296686
TempCoeff3_0 3.42202e+006
TempCoeff4_0 -2.00029e+007
TempCoeff5_0 5.6857e+007
TempCoeff6_0 -6.24299e+007
TempPolyOrder_0 6
TPFact 1.0
TPFact_0 1.0
Group Referenced Files
BgFile_0 
CAFile IRTV-007604.cal
DATA
