TOP=../..
include $(TOP)/configure/CONFIG
DB += dbSysMon.db
#DB += dbccsPT100.db
DB += dbicsPT100.db
DB += dbicsDI.db
#DB += dbccsPT100.template
#DB += dbSysMonTimestamp.db
DB += dbicsPT100.template
DB += dbicsDI.template
#add leesi
DB += dbPing.vdb
#DB += dbESDPV.db
DB += ESD_TF.vdb
include $(TOP)/configure/RULES

