TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#DB += dbExample1.db
#DB += dbExample2.db
#DB += dbSubExample.db
#DB += user.substitutions
#DB += userHost.substitutions


DB += MC_DAQ_AO.db
DB += MC_DAQ_AI.db
DB += MC_DAQ_BO.db
DB += MC_DAQ_MBBO.db
DB += MC_DAQ_MBBI.db
DB += MC_DAQ_MBBO2.db

DB += MC_DAQ_SOFT_MASTER_BO.db
DB += MC_DAQ_SOFT_MASTER_AO.db 
DB += MC_DAQ_SOFT_MASTER_MBBO.db 
DB += MC_DAQ_MDSNODE_STRING.db
DB += MC_DAQ_SOFT_MASTER_STRING.db

DB += MC_DAQ_AO_10S.template
DB += MC_DAQ_AI_10S.template
DB += MC_DAQ_BO_10S.template
DB += MC_DAQ_BO_S1.template
DB += MC_DAQ_BO_S2.template
DB += MC_DAQ_BO_S3.template
DB += MC_DAQ_BO_S4.template
DB += MC_DAQ_BO_S5.template
DB += MC_DAQ_BO_S6.template

DB += MC_DAQ_MBBO_10S.template
DB += MC_DAQ_MBBI_10S.template
DB += MC_DAQ_MBBO2_10S.template
DB += MC_DAQ_MBBO2_S1.template
DB += MC_DAQ_MBBO2_S2.template
DB += MC_DAQ_MBBO2_S3.template
DB += MC_DAQ_MBBO2_S4.template
DB += MC_DAQ_MBBO2_S5.template
DB += MC_DAQ_MBBO2_S6.template

DB += MC_DAQ_SOFT_MASTER_BO.template 
DB += MC_DAQ_SOFT_MASTER_AO.template 
DB += MC_DAQ_MDSNODE_STRING_10S.template
DB += MC_DAQ_MDSNODE_STRING_S1.template
DB += MC_DAQ_MDSNODE_STRING_S2.template
DB += MC_DAQ_MDSNODE_STRING_S3.template
DB += MC_DAQ_MDSNODE_STRING_S4.template
DB += MC_DAQ_MDSNODE_STRING_S5.template
DB += MC_DAQ_MDSNODE_STRING_S6.template

DB += MC_DAQ_BIO_CAL.db
DB += MC_DAQ_timeStamp.db
DB += dbSysMon.db
DB += dbSubNet.db
#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

