TOP = ../..

include $(TOP)/configure/CONFIG

LIBRARY_IOC_vxWorks += vmivme5565Rfm

DBDINC += rfmRecord
DBD += rfmSupport.dbd

vmivme5565Rfm_SRCS_vxWorks += drvVmivme5565.c
vmivme5565Rfm_SRCS_vxWorks += devRfm.c
vmivme5565Rfm_SRCS_vxWorks += rfmRecord.c

include $(TOP)/configure/RULES

