TOP = ../..
include $(TOP)/configure/CONFIG

DBDINC += timestampRecord

LIBRARY_IOC += recTimeStamp

recTimeStamp_SRCS += timestampRecord.c
recTimeStamp_SRCS += devTimestampSoft.c

include $(TOP)/configure/RULES
