TOP = ..
include $(TOP)/configure/CONFIG

MK80S = $(TOP)/MK80SLib

LIBRARY_IOC += MK80S

INC += drvMK80S.h
DBD += drvMK80S.dbd
DBD += devMK80S.dbd
MK80S_SRCS += drvMK80S.c
MK80S_SRCS += devMK80S.c

include $(TOP)/configure/RULES
