
TOP = ../..
include $(TOP)/configure/CONFIG


devSRSRGA_DIR += $(EPICS_PATH)/siteLib/lib/$(T_A)

DBD += devSRSRGA.dbd

LIBRARY_IOC    += devSRSRGA

devSRSRGA_SRCS += devSRSRGA.c


include $(TOP)/configure/RULES

