CFLAGS=-std=c99 -Wall
INCFLAGS=
LDFLAGS=
LIBS=-lOpenCL

all:
	#gcc $(CFLAGS) $(INCFLAGS) $(LDFLAGS) $(LIBS) -o opencl_info opencl_info.c
	gcc $(CFLAGS) $(INCFLAGS) $(LDFLAGS) $(LIBS) -o opencl_info opencl_info_ans.c

clean:
	rm -f opencl_info
