######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 23 16:13:55 2007
######################################################################

CONFIG += qt
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
SOURCES += main.cpp

target.path = ./PVSearch
sources.files = $$SOURCES $$HEADERS $$RESOURCES *.pro
sources.path = ./PVSearch
# install
INSTALLS += target sources
