TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += dbExample1.db
DB += dbExample2.db
DB += dbSubExample.db
DB += dlsHeartBeat.db
#DB += dlsShutter.db
#DB += dlsShutter.template
#DB += dlsShutter_p.db
#DB += dlsShutter_p.template
#Remove 20130219 DB += dlsShutter1_bo.db
#Remove 20130219 DB += dlsShutter1_bo.template
#Remove 20130219 DB += dlsShutter1p_bo.db
#Remove 20130219 DB += dlsShutter1p_bo.template
DB += dlsShutter2_bo.db
DB += dlsShutter2_bo.template
DB += dlsShutter2_bi.db
DB += dlsShutter2_bi.template
DB += dlsShutter2_mbbi.db
DB += dlsShutter2_mbbo.db
DB += dlsShutter2_mbbi.template
DB += dlsTimeStamp.db
DB += dbSysMon.db
DB += dlsPT100_3.db
DB += dlsPT100_3.template
DB += dlsShutter3_bo.db
DB += dlsShutter3_bo.template
DB += dlsShutter3p_bo.db
DB += dlsShutter3p_bo.template
DB += dlsShutter4_bo_soft.db
DB += dlsShutter4_bo_soft.template
DB += dlsShutter4_bo.db
DB += dlsShutter4_bo.template
DB += dlsShutter4_bi.db
DB += dlsShutter4_bi.template
DB += dlsShutter4_mbbi.db
DB += dlsShutter4_mbbi.template
DB += dlsShutterSoft_bo.db
#DB += dlsIntLockInterFace.db
#DB += dlsIntLockInterFace.template

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

