#Makefile at top of application tree
TOP = ..

include $(TOP)/configure/CONFIG

# SDN library for CCS v4.1
DIRS += sdn

# Example for SDN in CCS v4.0
DIRS += testcps

# Example for SDN in CCS v4.1
DIRS += testsdn

include $(TOP)/configure/RULES_TOP

