createPXITask("Dev4")

createPXICernoxChannel("Dev4", "SC4Mod1/ai0")
createPXICernoxChannel("Dev4", "SC4Mod1/ai1")
createPXICernoxChannel("Dev4", "SC4Mod1/ai2")
createPXICernoxChannel("Dev4", "SC4Mod1/ai3")
createPXICernoxChannel("Dev4", "SC4Mod1/ai4")
createPXICernoxChannel("Dev4", "SC4Mod1/ai5")
createPXICernoxChannel("Dev4", "SC4Mod1/ai6")
createPXICernoxChannel("Dev4", "SC4Mod1/ai7")

createPXICernoxChannel("Dev4", "SC4Mod2/ai0")
createPXICernoxChannel("Dev4", "SC4Mod2/ai1")
createPXICernoxChannel("Dev4", "SC4Mod2/ai2")
createPXICernoxChannel("Dev4", "SC4Mod2/ai3")
createPXICernoxChannel("Dev4", "SC4Mod2/ai4")
createPXICernoxChannel("Dev4", "SC4Mod2/ai5")
createPXICernoxChannel("Dev4", "SC4Mod2/ai6")
createPXICernoxChannel("Dev4", "SC4Mod2/ai7")

createPXICernoxChannel("Dev4", "SC4Mod3/ai0")
createPXICernoxChannel("Dev4", "SC4Mod3/ai1")
createPXICernoxChannel("Dev4", "SC4Mod3/ai2")
createPXICernoxChannel("Dev4", "SC4Mod3/ai3")
createPXICernoxChannel("Dev4", "SC4Mod3/ai4")
createPXICernoxChannel("Dev4", "SC4Mod3/ai5")
createPXICernoxChannel("Dev4", "SC4Mod3/ai6")
createPXICernoxChannel("Dev4", "SC4Mod3/ai7")

createPXICernoxChannel("Dev4", "SC4Mod4/ai0")
createPXICernoxChannel("Dev4", "SC4Mod4/ai1")
createPXICernoxChannel("Dev4", "SC4Mod4/ai2")
createPXICernoxChannel("Dev4", "SC4Mod4/ai3")
createPXICernoxChannel("Dev4", "SC4Mod4/ai4")
createPXICernoxChannel("Dev4", "SC4Mod4/ai5")
createPXICernoxChannel("Dev4", "SC4Mod4/ai6")
createPXICernoxChannel("Dev4", "SC4Mod4/ai7")

createPXICernoxChannel("Dev4", "SC4Mod5/ai0")
createPXICernoxChannel("Dev4", "SC4Mod5/ai1")
createPXICernoxChannel("Dev4", "SC4Mod5/ai2")
createPXICernoxChannel("Dev4", "SC4Mod5/ai3")
createPXICernoxChannel("Dev4", "SC4Mod5/ai4")
createPXICernoxChannel("Dev4", "SC4Mod5/ai5")
createPXICernoxChannel("Dev4", "SC4Mod5/ai6")
createPXICernoxChannel("Dev4", "SC4Mod5/ai7")

createPXICernoxChannel("Dev4", "SC4Mod6/ai0")
createPXICernoxChannel("Dev4", "SC4Mod6/ai1")
createPXICernoxChannel("Dev4", "SC4Mod6/ai2")
createPXICernoxChannel("Dev4", "SC4Mod6/ai3")
createPXICernoxChannel("Dev4", "SC4Mod6/ai4")
createPXICernoxChannel("Dev4", "SC4Mod6/ai5")
createPXICernoxChannel("Dev4", "SC4Mod6/ai6")
createPXICernoxChannel("Dev4", "SC4Mod6/ai7")

createPXICernoxChannel("Dev4", "SC4Mod7/ai0", "50")
createPXICernoxChannel("Dev4", "SC4Mod7/ai1", "50")
createPXICernoxChannel("Dev4", "SC4Mod7/ai2", "50")
createPXICernoxChannel("Dev4", "SC4Mod7/ai3", "50")
createPXICernoxChannel("Dev4", "SC4Mod7/ai4", "50")
createPXICernoxChannel("Dev4", "SC4Mod7/ai5", "50")

createPXICernoxChannel("Dev4", "SC4Mod8/ai0", "50")
createPXICernoxChannel("Dev4", "SC4Mod8/ai1", "50")
createPXICernoxChannel("Dev4", "SC4Mod8/ai2", "50")
createPXICernoxChannel("Dev4", "SC4Mod8/ai3", "50")
createPXICernoxChannel("Dev4", "SC4Mod8/ai4", "50")
createPXICernoxChannel("Dev4", "SC4Mod8/ai5", "50")
