createPXITask("Dev1")

createPXICernoxChannel("Dev1", "SC1Mod1/ai0")
createPXICernoxChannel("Dev1", "SC1Mod1/ai1")
createPXICernoxChannel("Dev1", "SC1Mod1/ai2")
createPXICernoxChannel("Dev1", "SC1Mod1/ai3")
createPXICernoxChannel("Dev1", "SC1Mod1/ai4")
createPXICernoxChannel("Dev1", "SC1Mod1/ai5")
createPXICernoxChannel("Dev1", "SC1Mod1/ai6")
createPXICernoxChannel("Dev1", "SC1Mod1/ai7")

createPXICernoxChannel("Dev1", "SC1Mod2/ai0")
createPXICernoxChannel("Dev1", "SC1Mod2/ai1")
createPXICernoxChannel("Dev1", "SC1Mod2/ai2")
createPXICernoxChannel("Dev1", "SC1Mod2/ai3")
createPXICernoxChannel("Dev1", "SC1Mod2/ai4")
createPXICernoxChannel("Dev1", "SC1Mod2/ai5")
createPXICernoxChannel("Dev1", "SC1Mod2/ai6")
createPXICernoxChannel("Dev1", "SC1Mod2/ai7")

createPXICernoxChannel("Dev1", "SC1Mod3/ai0")
createPXICernoxChannel("Dev1", "SC1Mod3/ai1")
createPXICernoxChannel("Dev1", "SC1Mod3/ai2")
createPXICernoxChannel("Dev1", "SC1Mod3/ai3")
createPXICernoxChannel("Dev1", "SC1Mod3/ai4")
createPXICernoxChannel("Dev1", "SC1Mod3/ai5")
createPXICernoxChannel("Dev1", "SC1Mod3/ai6")
createPXICernoxChannel("Dev1", "SC1Mod3/ai7")

createPXICernoxChannel("Dev1", "SC1Mod4/ai0")
createPXICernoxChannel("Dev1", "SC1Mod4/ai1")
createPXICernoxChannel("Dev1", "SC1Mod4/ai2")
createPXICernoxChannel("Dev1", "SC1Mod4/ai3")
createPXICernoxChannel("Dev1", "SC1Mod4/ai4")
createPXICernoxChannel("Dev1", "SC1Mod4/ai5")
createPXICernoxChannel("Dev1", "SC1Mod4/ai6")
createPXICernoxChannel("Dev1", "SC1Mod4/ai7")

createPXICernoxChannel("Dev1", "SC1Mod5/ai0")
createPXICernoxChannel("Dev1", "SC1Mod5/ai1")
createPXICernoxChannel("Dev1", "SC1Mod5/ai2")
createPXICernoxChannel("Dev1", "SC1Mod5/ai3")
createPXICernoxChannel("Dev1", "SC1Mod5/ai4")
createPXICernoxChannel("Dev1", "SC1Mod5/ai5")
createPXICernoxChannel("Dev1", "SC1Mod5/ai6")
createPXICernoxChannel("Dev1", "SC1Mod5/ai7")

createPXICernoxChannel("Dev1", "SC1Mod6/ai0")
createPXICernoxChannel("Dev1", "SC1Mod6/ai1")
createPXICernoxChannel("Dev1", "SC1Mod6/ai2")
createPXICernoxChannel("Dev1", "SC1Mod6/ai3")
createPXICernoxChannel("Dev1", "SC1Mod6/ai4")
createPXICernoxChannel("Dev1", "SC1Mod6/ai5")
createPXICernoxChannel("Dev1", "SC1Mod6/ai6")
createPXICernoxChannel("Dev1", "SC1Mod6/ai7")

createPXICernoxChannel("Dev1", "SC1Mod7/ai0")
createPXICernoxChannel("Dev1", "SC1Mod7/ai1")
createPXICernoxChannel("Dev1", "SC1Mod7/ai2")
createPXICernoxChannel("Dev1", "SC1Mod7/ai3")
createPXICernoxChannel("Dev1", "SC1Mod7/ai4")
createPXICernoxChannel("Dev1", "SC1Mod7/ai5")
createPXICernoxChannel("Dev1", "SC1Mod7/ai6")
createPXICernoxChannel("Dev1", "SC1Mod7/ai7")

createPXICernoxChannel("Dev1", "SC1Mod8/ai0")
createPXICernoxChannel("Dev1", "SC1Mod8/ai1")
createPXICernoxChannel("Dev1", "SC1Mod8/ai2")
createPXICernoxChannel("Dev1", "SC1Mod8/ai3")
createPXICernoxChannel("Dev1", "SC1Mod8/ai4")
createPXICernoxChannel("Dev1", "SC1Mod8/ai5")
createPXICernoxChannel("Dev1", "SC1Mod8/ai6")
createPXICernoxChannel("Dev1", "SC1Mod8/ai7")

createPXICernoxChannel("Dev1", "SC1Mod9/ai0")
createPXICernoxChannel("Dev1", "SC1Mod9/ai1")
createPXICernoxChannel("Dev1", "SC1Mod9/ai2")
createPXICernoxChannel("Dev1", "SC1Mod9/ai3")
createPXICernoxChannel("Dev1", "SC1Mod9/ai4")
createPXICernoxChannel("Dev1", "SC1Mod9/ai5")
createPXICernoxChannel("Dev1", "SC1Mod9/ai6")
createPXICernoxChannel("Dev1", "SC1Mod9/ai7")

createPXICernoxChannel("Dev1", "SC1Mod10/ai0")
createPXICernoxChannel("Dev1", "SC1Mod10/ai1")
createPXICernoxChannel("Dev1", "SC1Mod10/ai2")
createPXICernoxChannel("Dev1", "SC1Mod10/ai3")
createPXICernoxChannel("Dev1", "SC1Mod10/ai4")
createPXICernoxChannel("Dev1", "SC1Mod10/ai5")
createPXICernoxChannel("Dev1", "SC1Mod10/ai6")
createPXICernoxChannel("Dev1", "SC1Mod10/ai7")

createPXICernoxChannel("Dev1", "SC1Mod11/ai0")
createPXICernoxChannel("Dev1", "SC1Mod11/ai1")
createPXICernoxChannel("Dev1", "SC1Mod11/ai2")
createPXICernoxChannel("Dev1", "SC1Mod11/ai3")
createPXICernoxChannel("Dev1", "SC1Mod11/ai4")
createPXICernoxChannel("Dev1", "SC1Mod11/ai5")
createPXICernoxChannel("Dev1", "SC1Mod11/ai6")
createPXICernoxChannel("Dev1", "SC1Mod11/ai7")

createPXICernoxChannel("Dev1", "SC1Mod12/ai0")
createPXICernoxChannel("Dev1", "SC1Mod12/ai1")
createPXICernoxChannel("Dev1", "SC1Mod12/ai2")
createPXICernoxChannel("Dev1", "SC1Mod12/ai3")
createPXICernoxChannel("Dev1", "SC1Mod12/ai4")
createPXICernoxChannel("Dev1", "SC1Mod12/ai5")
createPXICernoxChannel("Dev1", "SC1Mod12/ai6")
createPXICernoxChannel("Dev1", "SC1Mod12/ai7")
