######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 25 08:27:10 2007
######################################################################
#CONFIG += uitools qt
TEMPLATE = app
MOC_DIR      = .moc
OBJECTS_DIR  = .obj

INCLUDEPATH += ../include/

#memcached lib
LIBS += -L/usr/local/lib -lmemcached -lpthread

# Input
SOURCES += MemcachedTest.cpp

# Output
TARGET = MemcachedTest

target.path = ./
INSTALLS += target
