TOP=../..
include $(TOP)/configure/CONFIG


DB += dbSysMon.db
DB += FUEL_AI.db
DB += FUEL_AI.template
DB += FUEL_AO.db
DB += FUEL_AO.template
DB += FUEL_BI.db
DB += FUEL_BI.template
DB += FUEL_BO.db
DB += FUEL_BO_SW.db
DB += FUEL_BO.template
DB += FUEL_HEART.db
DB += FUEL_PZ_EMO.db
DB += FUEL_REMOTE.db
DB += FUEL_TIME.db


include $(TOP)/configure/RULES

