TOP = ..
include $(TOP)/configure/CONFIG

VMEUNIVERSE = $(TOP)/vmeUniverseLib
LIBRARY_IOC += vmeUniverse

SRC_DIRS += $(VMEUNIVERSE)/drvvmeUniverse
INC += drvvmeUniverse.h
DBD += drvvmeUniverse.dbd
vmeUniverse_SRCS += drvvmeUniverse.c

include $(TOP)/configure/RULES

