TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this


DB += CLS_ai.db
DB += CLS_ai_P.db
DB += CLS_ai_REF.db
DB += CLS_ao.db
DB += CLS_bi.db
DB += CLS_BO_MANU.db
DB += CLS_BO_PLC.db
DB += CLS_FLOW.db
DB += CLS_He_AI_P.template
DB += CLS_He_AI_REF.template
DB += CLS_He_AI.template
DB += CLS_He_AO_FLOW.template
DB += CLS_He_AO_SP.template
DB += CLS_He_AO.template
DB += CLS_HEART.db
DB += CLS_He_BI.template
DB += CLS_He_BO_MANU.template
DB += CLS_He_BO_PLC.template

DB += CLS_HCS_AI_ALARM.db
DB += CLS_HCS_AI_ALARM.template
DB += CLS_HCS_AI.db
DB += CLS_HCS_AI.template
DB += CLS_HCS_AO.db
DB += CLS_HCS_AO.template
DB += CLS_HCS_BI.db
DB += CLS_HCS_BI.template
DB += CLS_HCS_BO.db
DB += CLS_HCS_BO_IN.db
DB += CLS_HCS_BO_IN.template
DB += CLS_HCS_BO.template
DB += CLS_HCS_RESET.db
DB += CLS_HCS_UTIL.db

DB += NEW_CLS_HCS_AO.db
DB += NEW_CLS_HCS_AO.template

DB += CLS_AO_TEMP.db
DB += CLS_AO_TEMP.template


DB += CLS_PF_RGA_FL.db
DB += CLS_PF_RGA_INIT.db
DB += CLS_PF_RGA_READ.db
DB += CLS_PF_RGA_READ.template
DB += CLS_TF_RGA_FL.db
DB += CLS_TF_RGA_INIT.db
DB += CLS_TF_RGA_READ.db
DB += CLS_TF_RGA_READ.template

DB += CLS_REMOTE.db
DB += CLS_TIME.db
DB += CLS_VPS_AI.db
DB += CLS_VPS_AI_GAUGE.db
DB += CLS_VPS_AI_GAUGE.template
DB += CLS_VPS_AI.template
DB += CLS_VPS_AO.db
DB += CLS_VPS_AO.template
DB += CLS_VPS_BI.db
DB += CLS_VPS_BI.template
DB += CLS_VPS_BO.db
DB += CLS_VPS_BO_SW.db
DB += CLS_VPS_BO.template
DB += CLS_VPS_GAUGE_AL.db
DB += CLS_VPS_GAUGE_AL.template
DB += CLS_VPS_HEART.db
DB += CLS_VPS_MBBI_TMP.db
DB += CLS_VPS_MBBI_TMP.template
DB += CLS_VPS_MBBI_TPG256.db
DB += CLS_VPS_MBBI_TPG256.template

DB += CLS_VPS_AI_TMP_I.db
DB += CLS_VPS_AI_TMP_I.template
DB += CLS_VPS_BI_ACCEL.db
DB += CLS_VPS_BI_ACCEL.template

DB += dbSysMon.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

