######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 25 08:27:10 2007
######################################################################
TEMPLATE = app

MOC_DIR      = .moc
OBJECTS_DIR  = .obj
DEPENDPATH  += include/
INCLUDEPATH += include/

# Input
SOURCES += Periodicscreenshot.cpp

# Output
TARGET =  Periodicscreenshot
target.path = /usr/local/opi/bin
INSTALLS += target
